"""alter_projects_table_relationships

Revision ID: 6221a911e623
Revises: aaa1adc81636
Create Date: 2024-02-02 15:56:48.454776

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6221a911e623'
down_revision: Union[str, None] = 'aaa1adc81636'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('project_owner_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'projects', 'users', ['project_owner_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'projects', type_='foreignkey')
    op.drop_column('projects', 'project_owner_id')
    # ### end Alembic commands ###
