version: "3.9"

services:
  postgres-db:
    container_name: postgres-db
    image: 'postgres'
    environment:
      POSTGRES_DB: ${POSTGRES_DB_NAME}
      POSTGRES_USER: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOSTNAME: ${POSTGRES_HOST}
      PGPORT: ${POSTGRES_PORT}
    network_mode: "host"

    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}
